"""add_scenario_violations_tablle

Revision ID: 2703a5f511d1
Revises: 
Create Date: 2023-12-01 15:59:46.968886

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2703a5f511d1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenario_violations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("trafo_id", sa.UUID(), nullable=True),
        sa.Column("trafo3w_id", sa.UUID(), nullable=True),
        sa.Column("bus_id", sa.UUID(), nullable=True),
        sa.Column("violation", sa.String(), nullable=False),
        sa.Column(
            "violated_values", sa.ARRAY(sa.Float(), as_tuple=True), nullable=False
        ),
        sa.Column("limit", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"], ["network_branches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["bus_id"], ["network_buses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["trafo3w_id"], ["network_trafos_3w.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["trafo_id"], ["network_trafos.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario_violations")
    # ### end Alembic commands ###
