"""update_indexes

Revision ID: 59ce47b4edd4
Revises: 3749eea677db
Create Date: 2023-12-21 10:48:59.660714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ce47b4edd4'
down_revision: Union[str, None] = '3749eea677db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_milestones_connection_request_id'), 'milestones', ['connection_request_id'], unique=False)
    op.create_index(op.f('ix_scenario_requests_m2m_connection_request_id'), 'scenario_requests_m2m', ['connection_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_requests_m2m_connection_request_id'), table_name='scenario_requests_m2m')
    op.drop_index(op.f('ix_milestones_connection_request_id'), table_name='milestones')
    # ### end Alembic commands ###
