name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install mypy black
    - name: Check formatting
      run: |
        black --exclude="migrations" --check ./backend
        mypy --install-types --non-interactive --ignore-missing-imports ./backend

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: maplibre
        
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install --non-interactive
    - run: yarn formatcheck
    - run: yarn lint
    - run: yarn build
