name: Backend Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip3 install mypy black

      - name: Check formatting
        run: black --exclude="migrations" --check .

      - name: Check linting
        run: mypy --install-types --non-interactive --ignore-missing-imports .

      - name: Run test suite
        run: pip3 install -r requirements.txt && python -m unittest
